#Server
ACTIVE_PROFILE: dev
CONTAINER_PORT: 8085


#Database
POSGRESQL_USERNAME: pgi
POSGRESQL_PASSWORD: pgi


POSTGRESQL_HOST: 0.0.0.0
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: warehouse_management

